### ISSUE TITLE
Changes on Login & Register and Improvements.

### ISSUE THREAD

**Issue by Mohd-Imtiyaz** [tamaraiselvan/Base-Django-project-Setup#1]
Please Try to keep Login and Register in Seperate pages and please try to increase the UI and UX of the pages.

Admin Dashboard and Admin pages is nice.

Please add Unique email feature while registration.

**Note:**
_Bug:_ Once entering wrong details in registration it is redirecting to another page of same registration.

@tamaraiselvan  Please workout on the issues and please consider my ideas. I hope you will slove and add the features soon.

Thank you.

**Comment by tamaraiselvan** [comment]
The issues and the Features you have asked is developed.

The [Version 2](https://github.com/tamaraiselvan/Base-django-project-Setup/releases/tag/v2.0) of the project has the updated code.

Thank you for your suggesstion. I congratulate you have found issues.

If you found further any issues or any improvements in the project please raise it, So that i will know it and can solve it and improve.

Thank you @Mohd-Imtiyaz .

**Comment by Mohd-Imtiyaz** [comment]
Thank you for considering my suggesstions and clearing the issues.
